### ISSUE TITLE
Failed to init component

### ISSUE THREAD

**Issue by Isaac-Tait** [svelte-society/sveltesociety.dev#129] opened 2021-01-21 00:47 UTC
After running `npm run dev` (not `npm run dev dev` which is what the CONTRIBUTION.md doc says... typo maybe?). I am able to run on localhost 5000. However, when I click **Recipes** or **Events** I get this error:

```
Failed to init component

<Index>

instance/sortedEvents<@nollup-int:///src/pages/events/index.svelte:633:43
instance@nollup-int:///src/pages/events/index.svelte:633:28
init@nollup-int:///node_modules/svelte/internal/index.mjs:1470:11
Events@nollup-int:///src/pages/events/index.svelte:669:7
createProxiedComponent@nollup-int:///node_modules/svelte-hmr/runtime/svelte-hooks.js:214:9
ProxyComponent@nollup-int:///node_modules/svelte-hmr/runtime/proxy.js:237:42
Proxy<Index>@nollup-int:///node_modules/svelte-hmr/runtime/proxy.js:302:11
create_default_slot@nollup-int:///node_modules/@roxi/routify/runtime/Route.svelte:296:21
create_slot@nollup-int:///node_modules/svelte/internal/index.mjs:61:29
create_fragment@nollup-int:///node_modules/@roxi/routify/runtime/decorators/Noop.svelte:19:34
init@nollup-int:///node_modules/svelte/internal/index.mjs:1485:37
Noop@nollup-int:///node_modules/@roxi/routify/runtime/decorators/Noop.svelte:86:7
createProxiedComponent@nollup-int:///node_modules/svelte-hmr/runtime/svelte-hooks.js:214:9
ProxyComponent@nollup-int:///node_modules/svelte-hmr/runtime/proxy.js:237:42
Proxy<Noop>@nollup-int:///node_modules/svelte-hmr/runtime/proxy.js:302:11
create_each_block@nollup-int:///node_modules/@roxi/routify/runtime/Route.svelte:394:21
create_if_block@nollup-int:///node_modules/@roxi/routify/runtime/Route.svelte:66:43
update@nollup-int:///node_modules/@roxi/routify/runtime/Route.svelte:514:17
update@nollup-int:///node_modules/svelte/internal/index.mjs:764:36
flush@nollup-int:///node_modules/svelte/internal/index.mjs:732:19

<Noop>

instance/sortedEvents<@nollup-int:///src/pages/events/index.svelte:633:43
instance@nollup-int:///src/pages/events/index.svelte:633:28
init@nollup-int:///node_modules/svelte/internal/index.mjs:1470:11
Events@nollup-int:///src/pages/events/index.svelte:669:7
createProxiedComponent@nollup-int:///node_modules/svelte-hmr/runtime/svelte-hooks.js:214:9
ProxyComponent@nollup-int:///node_modules/svelte-hmr/runtime/proxy.js:237:42
Proxy<Index>@nollup-int:///node_modules/svelte-hmr/runtime/proxy.js:302:11
create_default_slot@nollup-int:///node_modules/@roxi/routify/runtime/Route.svelte:296:21
create_slot@nollup-int:///node_modules/svelte/internal/index.mjs:61:29
create_fragment@nollup-int:///node_modules/@roxi/routify/runtime/decorators/Noop.svelte:19:34
init@nollup-int:///node_modules/svelte/internal/index.mjs:1485:37
Noop@nollup-int:///node_modules/@roxi/routify/runtime/decorators/Noop.svelte:86:7
createProxiedComponent@nollup-int:///node_modules/svelte-hmr/runtime/svelte-hooks.js:214:9
ProxyComponent@nollup-int:///node_modules/svelte-hmr/runtime/proxy.js:237:42
Proxy<Noop>@nollup-int:///node_modules/svelte-hmr/runtime/proxy.js:302:11
create_each_block@nollup-int:///node_modules/@roxi/routify/runtime/Route.svelte:394:21
create_if_block@nollup-int:///node_modules/@roxi/routify/runtime/Route.svelte:66:43
update@nollup-int:///node_modules/@roxi/routify/runtime/Route.svelte:514:17
update@nollup-int:///node_modules/svelte/internal/index.mjs:764:36
flush@nollup-int:///node_modules/svelte/internal/index.mjs:732:19
```

Came across this while working on issue #33 Is anyone else able to replicate it?

**Comment by HAUDRAUFHAUN** [comment] 2021-01-21 07:33
This issue is caused by an routify update. We try to fix this 👍🏻

**Comment by HAUDRAUFHAUN** [comment] 2021-01-21 14:19
The latest routify updates should resolve this. It's working now, so I'll close this issue.

**Closed by HAUDRAUFHAUN** 2021-01-21 14:19 UTC
